// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe03mNXRERSE34Q0vAn9n45e38a-BJ4as',
    appId: '1:1084110687618:web:999756b96a6a50bccb539b',
    messagingSenderId: '1084110687618',
    projectId: 'lostnfound-app-86997',
    authDomain: 'lostnfound-app-86997.firebaseapp.com',
    storageBucket: 'lostnfound-app-86997.appspot.com',
    measurementId: 'G-L6RPWJ5W5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJZA8hazPF2GMprz0VlZECAGGhLaYVVY',
    appId: '1:1084110687618:android:86210660a48f3cdfcb539b',
    messagingSenderId: '1084110687618',
    projectId: 'lostnfound-app-86997',
    storageBucket: 'lostnfound-app-86997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKAFBM73XwdVSqxjJHE7T_Zjy9AfDnevQ',
    appId: '1:1084110687618:ios:0f9e983e3d24256ccb539b',
    messagingSenderId: '1084110687618',
    projectId: 'lostnfound-app-86997',
    storageBucket: 'lostnfound-app-86997.appspot.com',
    iosBundleId: 'com.example.lostNFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKAFBM73XwdVSqxjJHE7T_Zjy9AfDnevQ',
    appId: '1:1084110687618:ios:0f9e983e3d24256ccb539b',
    messagingSenderId: '1084110687618',
    projectId: 'lostnfound-app-86997',
    storageBucket: 'lostnfound-app-86997.appspot.com',
    iosBundleId: 'com.example.lostNFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0sryg0c8xxz_qFQwE06NPCGaqjwouFeY',
    appId: '1:1084110687618:web:920f8d925c5ca25bcb539b',
    messagingSenderId: '1084110687618',
    projectId: 'lostnfound-app-86997',
    authDomain: 'lostnfound-app-86997.firebaseapp.com',
    storageBucket: 'lostnfound-app-86997.appspot.com',
    measurementId: 'G-R7PR905PT7',
  );

}